sac:
  env: navix/Navix-DoorKey-8x8-v0
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 131_072
  fill_buffer: 8_192
  batch_size: 1_028
  learning_rate: 0.0003
  gradient_steps: 128
  total_timesteps: 1_048_576
  eval_freq: 131_072
  gamma: 0.8
  tau: 0.9
  target_entropy_ratio: 0.6
  normalize_observations: true

ppo:
  env: navix/Navix-DoorKey-8x8-v0
  agent_kwargs:
    activation: tanh
  num_envs: 32
  num_steps: 128
  num_epochs: 8
  num_minibatches: 32
  learning_rate: 0.0003
  max_grad_norm: 10
  total_timesteps: 1_048_576
  eval_freq: 262_144
  gamma: 0.95
  gae_lambda: 0.99
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  normalize_observations: true

dqn:
  env: navix/Navix-DoorKey-8x8-v0
  agent_kwargs:
    activation: tanh
  num_envs: 128
  gradient_steps: 128
  buffer_size: 131_072
  fill_buffer: 8_192
  batch_size: 1_024
  learning_rate: 0.0003
  max_grad_norm: 1
  total_timesteps: 1_048_576
  eval_freq: 131_072
  gamma: 0.9
  eps_start: 1.0
  eps_end: 0.05
  exploration_fraction: 0.1
  target_update_freq: 1_024
  ddqn: true
  normalize_observations: false
